vim.keymap.set("n", "<leader>dbg", function()
	require("dapui").setup()
	require("dapui").open()
end)
vim.keymap.set("n", "<leader>dbc", function()
	require("dapui").close()
end)
vim.keymap.set("n", "<leader>db", "<cmd>DapToggleBreakpoint<cr>")
vim.keymap.set("n", "<leader>dc", "<cmd>DapContinue<cr>")
vim.keymap.set("n", "<leader>do", "<cmd>DapStepOver<cr>")
vim.keymap.set("n", "<leader>dso", "<cmd>DapStepOut<cr>")
vim.keymap.set("n", "<leader>dsi", "<cmd>DapStepInto<cr>")
vim.keymap.set("n", "<leader>dt", "<cmd>DapTerminate<cr>")
